source 'https://rubygems.org'
ruby '3.0'

gem 'rspec'
gem 'faker'
# gem 'capybara'
gem 'httpclient'
gem 'pry'
gem 'selenium-webdriver'
gem 'rest-client'
gem 'addressable'
gem 'chromedriver-helper'
gem 'rest'
gem 'nokogiri'
# gem 'rubocop'
# gem 'gmail'
gem 'dotenv'
# gem 'luhnacy'
gem 'json'
gem 'jsonclient'
gem 'aws-sdk'
gem 'dotenv'
# gem 'tzinfo'
# gem 'certified'
# gem 'jwt'
# gem 'crack'
# gem "allure-rspec", '~> 2.13.6'
# gem 'xmlrpc/client'
gem 'etc'
gem 'aws-sdk-s3'
